# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Build and upload the release to Diawi for internal testing, then send URL to Slack channel"
lane :dev do
    get_certificates(
        username: "alexandru.stratu+1@udevoffice.ro",
        team_id: "V8446ZTNQ4"
    )
    get_provisioning_profile(
        username: "alexandru.stratu+1@udevoffice.ro",
        app_identifier: "com.udevoffice.decoupled.net",
        team_id: "V8446ZTNQ4"
    )
    build_app
    diawi(
        token: "A1gHcmSwKkpcx9KfjBv7DO2J7Jul0Q4VFEGCg7dtzV",
        file: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
    slack(
        message: "*** iOS app *** ready to download on Diawi: " + lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI], slack_url: "https://hooks.slack.com/services/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"
    )
    clean_build_artifacts
end
